### ISSUE TITLE
TS support

### ISSUE THREAD

**Issue by AlenDavid** [mattdesl/yyz#1]
It would be great if this project had Typescript support!

**Comment by mattdesl** [comment]
Since this is built on top of esbuild it should work already, perhaps I have to enable something though.

**Comment by mattdesl** [comment]
Should be fixed now, can do `node . sketches/Test.ts` to test a TypeScript example. I don't know much about TypeScript, feel free to submit a PR if you'd like to clean up the test with more TypeScript-y style.

Ideally I'd like typings for this project and its API but I'm not sure I'm prepared to write everything in TypeScript, so will have to find another way to generate them.

**Comment by titouanmathis** [comment]
JS Docs might be a good option in order to have types without a full rewrite in TypeScript (see the [webpack sources](https://github.com/webpack/webpack) for examples). It does not allow to use all of TypeScript features though.

I could try to add some basic types if needed / wanted.
