### ISSUE TITLE
1 high severity vulnerability

### ISSUE THREAD

**Issue by nucliweb** [mattdesl/yyz#2]
Thanks a lot for sharing @mattdesl 😊

### After install the dependencies you can see 1 high severity vulnerability

<img width="800" alt="Screen Shot 2020-11-12 at 22 08 27" src="https://user-images.githubusercontent.com/1307927/98996829-d3172000-2533-11eb-9e9d-9f0807a91f26.png">

**Comment by mattdesl** [comment]
Thanks. Can actually remove this dependency, as it’s not used.

**Comment by mattdesl** [comment]
Should be fixed now.
